version: '3.8'

services:
  db:
    image: postgres:13
    container_name: shareit-db
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: shareit_user
      POSTGRES_PASSWORD: shareit_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
